// Thin vector-index layer over the store's embedding column. Keeps the
// current model fingerprint + stats in a dedicated `vector_meta` table so the
// index can detect drift (embeddings generated by a different model) and the
// Web panel can report index health. The heavy lifting (cosine search) lives
// in store.searchVector; this module owns the index lifecycle.

const META_SCHEMA = `
CREATE TABLE IF NOT EXISTS vector_meta (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL
);
`;

export function createVectorIndex({ store, logger }) {
  const db = store.db;
  db.exec(META_SCHEMA);

  function getMeta(key) {
    const row = db.prepare("SELECT value FROM vector_meta WHERE key = ?").get(key);
    return row?.value ?? undefined;
  }

  function setMeta(key, value) {
    db.prepare(
      `INSERT INTO vector_meta (key, value) VALUES (?, ?)
       ON CONFLICT(key) DO UPDATE SET value = excluded.value`
    ).run(key, String(value));
  }

  return {
    /** Record the model that generated the current vectors. */
    markModel(modelHash, dimension) {
      setMeta("model_hash", modelHash);
      setMeta("dimension", String(dimension ?? ""));
      setMeta("updated_at", new Date().toISOString());
    },

    modelHash() {
      return getMeta("model_hash");
    },

    dimension() {
      const raw = getMeta("dimension");
      return raw && Number.isInteger(Number(raw)) ? Number(raw) : undefined;
    },

    /** Store (or clear with null vector) one memory's embedding. */
    saveEmbedding(id, vector) {
      store.setEmbedding(id, vector);
    },

    /** Drop one memory's embedding. */
    deleteEmbedding(id) {
      store.setEmbedding(id, null);
    },

    /** Read one memory's cached vector; undefined when none/parse failure. */
    getEmbedding(id) {
      const row = db.prepare("SELECT embedding FROM memories WHERE id = ?").get(id);
      if (!row?.embedding) return undefined;
      try {
        const v = JSON.parse(row.embedding);
        return Array.isArray(v) && v.length ? v : undefined;
      } catch {
        return undefined;
      }
    },

    /** Cosine search over embedded rows; results carry a 0..1 score. */
    search(queryVector, { limit = 20, threshold = 0.65 } = {}) {
      return store.searchVector(queryVector, { limit, threshold });
    },

    /** Re-embed every row missing an embedding. Returns indexed count. */
    async rebuildIndex(embedder, { limit = 1000 } = {}) {
      if (!embedder || typeof embedder.embedSingle !== "function") return { indexed: 0, skipped: 0 };
      const rows = store.needsEmbedding(limit);
      let indexed = 0;
      for (const row of rows) {
        try {
          const text = [row.title, row.content].filter(Boolean).join("\n");
          const vector = await embedder.embedSingle(text);
          if (vector && vector.length) {
            store.setEmbedding(row.id, vector);
            indexed++;
          }
        } catch (error) {
          logger?.warn?.(`[dsh-mneme] rebuild embed failed for ${row.id}: ${String(error)}`);
        }
      }
      if (indexed > 0 && embedder.modelHash) this.markModel(embedder.modelHash, embedder.dimension);
      return { indexed, skipped: rows.length - indexed };
    },

    /** Index stats for the Web panel / debugging. */
    getStats() {
      return {
        modelHash: getMeta("model_hash"),
        dimension: this.dimension(),
        updatedAt: getMeta("updated_at"),
        embeddedCount: store.embeddedCount(),
        totalCount: store.count()
      };
    }
  };
}
