import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
// src/ is the single source of truth for every module (including the Web
// client bundle); lib/ is build output produced by `npm run sync`.
const clientSource = readFileSync(join(root, "src/client.js"), "utf8");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

// The Web client bundle registers itself via __ModuleLoader__.load. DSH
// resolves the bundle by plugin package name, so the registered id must match
// package.json `name` exactly (a mismatch surfaces as "loaded without
// registering '@modusensus/dsh-mneme'" in the DSH client).
test("client bundle registers under the package name", () => {
  const match = clientSource.match(/__ModuleLoader__\.load\(\{\s*id:\s*"([^"]+)"/);
  assert.ok(match, "client bundle must call __ModuleLoader__.load with an id");
  assert.equal(match[1], pkg.name, "registered id must equal package.json name");
});

// client.js is authored under src/ like every other module; lib/client.js is
// build output generated by `npm run sync` (prepack), so it must stay a
// byte-identical copy — drift here means the sync wasn't run.
test("client bundle is src-authored and synced into lib", () => {
  assert.equal(existsSync(join(root, "src/client.js")), true, "src/client.js must exist");
  assert.equal(existsSync(join(root, "lib/client.js")), true, "lib/client.js must exist");
  const libClient = readFileSync(join(root, "lib/client.js"), "utf8");
  assert.equal(libClient, clientSource, "lib/client.js must equal src/client.js (run `npm run sync`)");
});

// The memory entry lives at the sidebar foot, not in the settings modal: the
// migration must register into `sidebar.footer.action` (the list slot the
// sidebar shell renders beside Settings) and must not keep a `settings.section`
// registration, or the entry would appear twice under different hosts.
test("memory entry registers into the sidebar foot slot", () => {
  assert.ok(
    clientSource.includes('ctx.slots.inject("sidebar.footer.action"'),
    "client must inject into sidebar.footer.action"
  );
  assert.equal(
    clientSource.includes('"settings.section"'),
    false,
    "the old settings.section registration must be gone"
  );
});

// The drawer era is over as the PRIMARY surface: the sidebar entry must
// activate the main-area memory library tab first. The one sanctioned
// exception is the hero screen — the host hides the whole tab ring while a
// session is blank, so activation legitimately fails there and the same
// click falls back to a full-viewport overlay (same MemoryExplorer, not the
// old 420px side drawer). A dialog role stays banned either way.
test("tab-first activation with hero-screen overlay fallback", () => {
  assert.equal(
    clientSource.includes("role: \"dialog\""),
    false,
    "no dialog surface should remain"
  );
  assert.ok(
    clientSource.includes("activateExplorerTab(t(\"memory.view.label\"))"),
    "the sidebar trigger must activate the memory library tab by its label"
  );
  assert.ok(
    clientSource.includes("activateExplorerTab(t(\"memory.view.label\")).then((ok) => { if (!ok) setOpen(true); })"),
    "a failed tab activation must open the fallback overlay"
  );
  assert.ok(
    /if \(candidates\.length === 0\) \{ resolve\(false\); return; \}/.test(clientSource),
    "activation must resolve false when the tab ring is absent (hero screen)"
  );
  assert.ok(
    /aria-selected.*true/.test(clientSource),
    "activation is only confirmed once the host marks the tab selected"
  );
  // Same-labelled tabs from other plugins must never be activated by mistake:
  // the click is only trusted once OUR explorer view actually rendered, and
  // hidden tab panes are excluded before any click happens.
  assert.ok(
    /querySelector\("\.mneme-x"\) !== null/.test(clientSource),
    "activation must verify the memory explorer rendered, not just the tab state"
  );
  assert.ok(
    /offsetParent === null/.test(clientSource),
    "hidden tab panes (settings dialogs etc.) must be excluded from activation"
  );
});

// The fallback overlay reuses the full MemoryExplorer (three columns, graph,
// settings) at viewport size — not the old side drawer — and closes on Esc
// or the close button.
test("hero fallback overlay is a full-viewport MemoryExplorer with a close affordance", () => {
  assert.ok(
    clientSource.includes('.mneme-overlay{position:fixed;inset:0'),
    "the overlay must cover the full viewport"
  );
  assert.ok(
    clientSource.includes('h(MemoryExplorer, { t })'),
    "the overlay renders the same MemoryExplorer component as the tab"
  );
  assert.ok(
    clientSource.includes('e.key === "Escape"'),
    "Esc must close the overlay"
  );
  assert.ok(
    clientSource.includes('"memory.overlay.close"'),
    "the overlay ships a localized close label in both dictionaries"
  );
});

// The sidebar hands each footer action only its column state: a wide row
// (icon + label) when expanded, a bare rail icon when collapsed.
test("trigger renders a wide row or a rail icon from the wide flag", () => {
  assert.ok(
    /wide \? "mneme-trigger" : "mneme-trigger mneme-rail"/.test(clientSource),
    "trigger must branch on the wide flag"
  );
  assert.ok(
    /wide && h\("span", \{ className: "mneme-trigger-label" \}/.test(clientSource),
    "the label span must render only when wide"
  );
});

// The full-width memory browser lives in the conversation view ring beside
// Chat / Trajectory, so the client must inject into `conversation.view` with
// a stable entry id (the active view is persisted by that id).
test("explorer registers into the conversation view ring", () => {
  assert.ok(
    clientSource.includes('ctx.slots.inject("conversation.view"'),
    "client must inject into conversation.view"
  );
  assert.ok(
    clientSource.includes('id: "dsh-mneme-memory"'),
    "the view entry needs a stable, unique id"
  );
  assert.ok(
    clientSource.includes('"memory.view.label"'),
    "the tab label must come from the memory.view.label dictionary key"
  );
});

// The graph toggle must not read as "share": the primitives share icon is
// banned and a custom node-graph glyph takes its place.
test("graph toggle uses a node-graph glyph, not the share icon", () => {
  assert.equal(
    clientSource.includes("IconShareOutline16"),
    false,
    "IconShareOutline16 reads as share and must not appear"
  );
  assert.ok(
    clientSource.includes("GraphNodesIcon"),
    "the custom node-graph icon must back the graph toggle"
  );
});

// Every memory feature lives in the main-area library now: the explorer
// hosts six sub-views (browse / overview / directory / status / graph /
// settings) switched by tabs whose labels come from dedicated dictionary keys.
test("explorer hosts browse, overview, directory, status, graph and settings sub-views", () => {
  for (const key of ["tabMemory", "tabOverview", "tabDirectory", "tabStatus", "tabGraph", "tabSettings"]) {
    assert.ok(
      clientSource.includes(`"memory.explorer.${key}"`),
      `sub-view labels must come from memory.explorer.${key}`
    );
  }
  assert.ok(
    clientSource.includes('h(GraphPanel, { t, focusEntity: graphFocus, onJumpMemory: jumpToMemory })'),
    "the graph panel must be embedded as a sub-view"
  );
  assert.ok(
    clientSource.includes('h(StatusPanel, { t })'),
    "the status panel must be embedded as a sub-view"
  );
  assert.ok(
    clientSource.includes('h(SettingsContent, { t })'),
    "the settings forms must be embedded as a sub-view"
  );
});

// The graph panel jumps back into the browser: related-memory rows and the
// edge source button must land on the browse tab with the target selected.
test("graph jump lands on the selected memory in the browser", () => {
  assert.ok(
    /onClick: \(\) => onJumpMemory && onJumpMemory\(m\)/.test(clientSource),
    "related-memory rows must jump via onJumpMemory(m)"
  );
  assert.ok(
    clientSource.includes("onJumpMemory({ id: selected.edge.memory_id })"),
    "the edge source button must jump to the origin memory by id"
  );
  assert.ok(
    /const jumpToMemory = \(target\) => \{/.test(clientSource),
    "jumpToMemory must reset filters and select the target"
  );
});

// "entity:" in the browser search is the graph entry grammar: it must offer
// a jump chip instead of filtering the list.
test("entity: search grammar offers a graph jump", () => {
  assert.ok(
    clientSource.includes('query.trim().startsWith("entity:")'),
    "the entity: prefix must be recognized"
  );
  assert.ok(
    /onClick: \(\) => openGraphFor\(entityQuery\)/.test(clientSource),
    "the jump chip must switch to the graph sub-view"
  );
});

// The explorer is a three-pane layout: types with counts, a month→day time
// tree, and a detail pane rendering the untruncated content.
test("explorer lays out types, timeline, and full-text detail", () => {
  assert.ok(
    clientSource.includes('className: "mneme-xmain"'),
    "the three-column grid must be present"
  );
  assert.ok(
    clientSource.includes('className: "mneme-xdcontent"'),
    "the detail pane must render the full content"
  );
  assert.ok(
    /toLocaleDateString\(undefined, \{ year: "numeric", month: "long" \}\)/.test(clientSource),
    "month groups must format via the host locale, not hardcoded strings"
  );
});

// The library page must read as a first-party view: the chrome resolves to
// the host's design tokens (layer-1 canvas, brand-blue active states) and
// the boxed-panel / pill-chip patterns of the drawer era must stay gone.
test("explorer chrome aligns with the host design system", () => {
  assert.ok(
    clientSource.includes("background:var(--dsw-alias-bg-layer-1)"),
    "the page canvas must sit on the host bg-layer-1 token"
  );
  assert.ok(
    /\.mneme-vtab\.mneme-active::after/.test(clientSource),
    "active sub-tabs use the host underline treatment"
  );
  assert.ok(
    clientSource.includes(".mneme-vtab.mneme-active{color:var(--dsw-alias-state-business-primary)}"),
    "active sub-tab text must turn the host brand blue"
  );
  assert.equal(
    /\.mneme-xmain\{[^}]*border:1px/.test(clientSource),
    false,
    "the three-column layout must not wrap itself in a boxed panel"
  );
  assert.equal(
    clientSource.includes("border-radius:999px"),
    false,
    "pill chips belong to the drawer era and must stay gone"
  );
});

// The v0.6.1 wiki-link feature: the detail pane mounts a BacklinksPanel that
// fetches the two read-only link endpoints by the selected memory id and
// renders back/forward rows, each jumping back into the browser.
test("detail pane mounts a BacklinksPanel backed by the two link endpoints", () => {
  assert.ok(
    clientSource.includes("h(BacklinksPanel, { memory: selected, t, onJump: jumpToMemory })"),
    "the detail pane must mount BacklinksPanel after the actions row"
  );
  assert.ok(
    clientSource.includes("/api/dsh-mneme/wikilinks/backlinks?id="),
    "BacklinksPanel must fetch the backlinks endpoint by memory id"
  );
  assert.ok(
    clientSource.includes("/api/dsh-mneme/wikilinks/forward?id="),
    "BacklinksPanel must fetch the forward-links endpoint by memory id"
  );
});

// Detail content turns [[target]] / [[display|target]] into clickable links:
// the display text survives, the target title is kept for hover, and a click
// resolves the title through the resolve endpoint before jumping.
test("detail content renders wiki-links and resolves them on click", () => {
  assert.ok(
    clientSource.includes('className: "mneme-wikilink"'),
    "inline [[target]] links must use the .mneme-wikilink style"
  );
  assert.ok(
    clientSource.includes("/api/dsh-mneme/wikilinks/resolve?title="),
    "clicking a wiki-link must resolve the title via the resolve endpoint"
  );
  assert.ok(
    clientSource.includes('className: "mneme-backlinks"'),
    "the panel must render inside a .mneme-backlinks block"
  );
});

// v0.6.2 tag system: the detail pane renders tags as clickable chips wired to
// the memory/tags endpoints, and a tag: query always goes server-side.
test("detail pane renders editable tag chips backed by the tags endpoint", () => {
  assert.ok(
    clientSource.includes("/api/dsh-mneme/memory/tags?id="),
    "the panel must fetch the selected memory's tags via the GET endpoint"
  );
  assert.ok(
    clientSource.includes('method: "POST"'),
    "adding/removing a tag must POST to the tags endpoint"
  );
  assert.ok(
    clientSource.includes("onClick: () => onTagClick(tag)"),
    "a tag chip click must trigger a tag: search"
  );
  assert.ok(
    clientSource.includes("tagManual"),
    "the panel must read the manualTagEnabled gate to hide editing"
  );
});

// The browse search is fully server-side now: every query rides the search
// endpoint — keyword = literal text (default), vector = semantic ranking via
// the semantic toggle — so matches are global, not limited to loaded pages.
// tag: chips still set a tag:<tag> query which rides the same endpoint.
test("search runs server-side for every query (keyword default, vector via the semantic toggle)", () => {
  assert.ok(
    clientSource.includes('const mode = semantic ? "vector" : "keyword";'),
    "the search mode must flip between keyword and vector with the semantic toggle"
  );
  assert.ok(
    clientSource.includes("&mode=${mode}"),
    "the search endpoint must receive the selected mode"
  );
  assert.ok(
    clientSource.includes('setQuery(`tag:${tag}`)'),
    "a tag chip click must set the query to tag:<tag>"
  );
});

test("tag UI ships localized labels in both dictionaries", () => {
  for (const key of ["tagAdd", "tagRemove", "tagPlaceholder", "tagsEmpty"]) {
    assert.ok(
      clientSource.includes(`"memory.explorer.${key}"`),
      `memory.explorer.${key} key must exist`
    );
  }
});

// v0.6.3 directory view: a tag-folder tree backed by the directory endpoint.
// Folders accordion via data-expanded controlled by MemoryExplorer-lifted
// state; a memory entry click jumps back into the browser via onJump.
test("directory sub-view mounts DirectoryPanel backed by the directory endpoint", () => {
  assert.ok(
    clientSource.includes("h(DirectoryPanel, { t, onJump: jumpToMemory, collapsed: dirCollapsed, setCollapsed: setDirCollapsed })"),
    "the directory panel must be embedded as a sub-view with lifted collapse state"
  );
  assert.ok(
    clientSource.includes("/api/dsh-mneme/directory"),
    "DirectoryPanel must fetch the directory endpoint"
  );
  assert.ok(
    clientSource.includes('className: "mneme-directory"'),
    "the directory panel must render inside the .mneme-directory block"
  );
});

test("directory folders accordion via data-expanded driven by MemoryExplorer state", () => {
  assert.ok(
    clientSource.includes('"data-expanded": String(open)'),
    "folder expansion must be driven by the data-expanded attribute"
  );
  assert.ok(
    clientSource.includes("const [dirCollapsed, setDirCollapsed] = useState({})"),
    "collapse state must live in MemoryExplorer so tab switches keep it"
  );
  assert.ok(
    clientSource.includes('"aria-expanded": String(open)'),
    "folder headers must announce their expanded state"
  );
});

test("directory entry click jumps to the memory detail via onJump", () => {
  assert.ok(
    clientSource.includes("onClick: () => onJump(m)"),
    "clicking a memory entry must call onJump with the memory"
  );
  assert.ok(
    clientSource.includes("formatDate(m.updated_at || m.created_at)"),
    "entries must render a timestamp via formatDate"
  );
  assert.ok(
    clientSource.includes("memory.directory.untagged"),
    "untagged memories must be bucketed under a labeled fallback folder"
  );
});

test("directory ships localized labels in both dictionaries", () => {
  for (const key of ["memory.explorer.tabDirectory", "memory.directory.untagged", "memory.directory.loading", "memory.directory.empty"]) {
    assert.ok(
      clientSource.includes(`"${key}"`),
      `${key} key must exist`
    );
  }
});

// issue #35: the delete confirm step must not depend on the host window.confirm —
// in the DSH web host the native dialog is unreliable/blocked, so clicks
// appeared to do nothing. Deletion is now an inline two-step confirm
// (✕ → 确认？ → DELETE), gated per row by confirmingId.
test("delete flow drops window.confirm for an inline two-step confirm", () => {
  assert.equal(
    /window\.confirm\(/.test(clientSource),
    false,
    "the delete path must not call the host window.confirm"
  );
  assert.ok(
    clientSource.includes("confirmingId"),
    "a per-row confirm state must gate the second click"
  );
  assert.ok(
    clientSource.includes('"directory.deleteConfirmShort"'),
    "the short inline confirm label must be localized"
  );
});

// issue #35: a failed DELETE (network / 401 / 500 / deleted!==true) must be
// visible — the old code swallowed it with a bare return and .catch(() => {}).
test("delete failure surfaces visible error feedback", () => {
  assert.ok(
    clientSource.includes("delErrorId"),
    "a per-row error state must track failed deletes"
  );
  assert.ok(
    clientSource.includes('"directory.deleteError"'),
    "the delete error message must be localized"
  );
  assert.ok(
    clientSource.includes(".mneme-dir-error"),
    "a failed row must get a visible error style"
  );
});

// issue #38: the sidebar foot trigger must be disableable so it stops colliding
// with other plugins that also claim the bottom-left footer slot (dsh-cost-meter
// et al). The client reads the settings-over-config toggle from the /config
// endpoint and renders no button when it is off; the 记忆库 conversation tab is
// unaffected, so nothing is lost by hiding the entry.
test("sidebar trigger is hidden when showSidebarTrigger is false (issue #38)", () => {
  assert.ok(
    clientSource.includes('apiFetch("/api/dsh-mneme/config")'),
    "trigger must read the effective config from /api/dsh-mneme/config"
  );
  assert.ok(
    /d\.config\?\.showSidebarTrigger !== false/.test(clientSource),
    "trigger must hide when showSidebarTrigger is explicitly false and stay visible by default"
  );
  assert.ok(
    clientSource.includes('"memory.settings.sidebarTriggerTitle"'),
    "settings panel must expose a sidebar-trigger toggle"
  );
});

// --- 0.7.11/0.7.12 panel port: paged chrono browse + month collapse, server
// search, status sub-view, two-step delete + importance filter, runtime-mode /
// external-API setting cards and the inline stroke icon system ---

// Browse streams 100-row pure-chronological pages (order=chrono): the default
// importance ordering would interleave months across pages and break the
// month tree. A sentinel auto-pulls the next page; a button does it manually.
test("browse loads 100-row chronological pages with a load-more sentinel", () => {
  assert.ok(
    clientSource.includes("const PAGE_SIZE = 100;"),
    "the browse page size must be 100 rows"
  );
  assert.ok(
    clientSource.includes("&order=chrono"),
    "browse pages must stream in pure chronological order"
  );
  assert.ok(
    /apiFetch\(listUrl\(items\.length\)\)/.test(clientSource),
    "loadMore must fetch the next offset page"
  );
  assert.ok(
    clientSource.includes("new IntersectionObserver"),
    "a sentinel must auto-pull the next page on scroll"
  );
  assert.ok(
    clientSource.includes('"memory.explorer.loadMore"'),
    "the load-more affordance must be localized"
  );
});

// Only the newest month starts expanded; older months stay one-line sticky
// headers (with a per-month count) until clicked.
test("month tree collapses to the newest month with sticky headers and counts", () => {
  assert.ok(
    clientSource.includes("const [expandedMonths, setExpandedMonths] = useState(null);"),
    "null expandedMonths must mean only the newest month is open"
  );
  assert.ok(
    clientSource.includes("const open = expandedMonths ? !!expandedMonths[month.key] : mi === 0;"),
    "the newest month (mi === 0) must start open, older ones closed"
  );
  assert.ok(
    clientSource.includes(".mneme-xmonth{position:sticky"),
    "month headers must stick to the top of the timeline card"
  );
  assert.ok(
    clientSource.includes('"mneme-xmonthcount"'),
    "each month header must carry its entry count"
  );
});

// The memory sub-view refreshes on activation and quietly re-fetches page 1
// every 30s while visible; hidden pages must not trigger fetches.
test("memory sub-view refreshes on activation and polls quietly every 30s", () => {
  assert.ok(
    clientSource.includes('if (document.visibilityState === "visible") refreshFirstPage();'),
    "the 30s poll must pause while the page is hidden"
  );
  assert.ok(
    clientSource.includes("}, 30000);"),
    "the live-view poll interval is 30 seconds"
  );
  assert.ok(
    clientSource.includes("if (view !== \"memory\") return undefined;"),
    "the live-view polling must only run while the browse tab is open"
  );
});

// Importance floor chips (全部/★3+/★4+/★5) filter server-side together with
// the type filter so pagination and totals stay consistent.
test("importance filter chips travel server-side with the type filter", () => {
  assert.ok(
    clientSource.includes("&minImportance=${minImp}"),
    "the importance floor must be a server-side query parameter"
  );
  assert.ok(
    /\[0, 3, 4, 5\]\.map/.test(clientSource),
    "the filter bar must offer the all/★3+/★4+/★5 chips"
  );
  assert.ok(
    clientSource.includes('t("memory.explorer.importance")'),
    "the chip group must be labeled with the localized importance heading"
  );
});

// The detail pane delete is a two-step confirm (red outline arms, solid red
// commits) posting to /delete; success removes the row locally and shrinks
// the total, failure surfaces a transient error note.
test("detail delete is a two-step confirm posting /delete", () => {
  assert.ok(
    clientSource.includes('apiFetch("/api/dsh-mneme/delete"'),
    "the detail pane must POST to the delete endpoint"
  );
  assert.ok(
    clientSource.includes('"memory.explorer.confirmDelete"') &&
      clientSource.includes('"memory.explorer.cancel"'),
    "the confirm/cancel step must be localized"
  );
  assert.ok(
    clientSource.includes("setTotal((n) => Math.max(0, n - 1))"),
    "a successful delete must shrink the server total locally"
  );
  assert.ok(
    clientSource.includes(".mneme-btndanger{"),
    "the delete affordance must use the red outline/solid danger styles"
  );
  assert.ok(
    !/window\.confirm\(/.test(clientSource.slice(clientSource.indexOf("const deleteSelected"))),
    "the detail delete path must not rely on window.confirm"
  );
});

// The status sub-view is a grid of four stat cards, each with its own
// fetch/loading/error state so one failing endpoint never blocks the others.
test("status sub-view renders four independent stat cards", () => {
  for (const ep of [
    "/api/dsh-mneme/list?limit=1&order=chrono",
    "/api/dsh-mneme/entities?limit=500",
    "/api/dsh-mneme/vector-config",
    "/api/dsh-mneme/semantic/llm-audit/stats?days=7"
  ]) {
    assert.ok(
      clientSource.includes(ep),
      `status cards must fetch ${ep}`
    );
  }
  assert.ok(
    clientSource.includes("function StatusCard({ t, title, loading, error, num, cap })"),
    "every status card must own its loading/error state"
  );
});

// Two boxed settings cards: runtime mode (light/standard chips, PUT /mode,
// restart hint, light-mode off-list) and the external access API (enable
// chips, host/port with validation, server-owned read-only token with copy).
test("settings ship runtime-mode and external-API cards", () => {
  assert.ok(
    clientSource.includes('apiFetch("/api/dsh-mneme/mode"'),
    "the mode card must read /mode"
  );
  assert.ok(
    clientSource.includes("body: JSON.stringify({ mode: next })"),
    "the mode card must PUT the selected mode"
  );
  assert.ok(
    clientSource.includes('"memory.settings.mode.offList"'),
    "light mode must show the disabled-features hint"
  );
  assert.ok(
    clientSource.includes('apiFetch("/api/dsh-mneme/external-api"'),
    "the external-API card must read /external-api"
  );
  assert.ok(
    clientSource.includes('t("memory.settings.extapi.invalidPort")'),
    "the port input must be validated (1-65535)"
  );
  assert.ok(
    clientSource.includes("mneme-set-token"),
    "the server-owned token must render read-only with a copy affordance"
  );
  assert.ok(
    clientSource.includes(".mneme-set-card{"),
    "the two cards must use the boxed card style"
  );
});

// The explorer ships an inline Lucide stroke icon system (no runtime
// dependency): path data tuples rendered by the Icon component, replacing
// text arrows and ad-hoc glyphs across the panel.
test("the explorer ships an inline stroke icon system", () => {
  assert.ok(
    clientSource.includes("const ICON_PATHS = {"),
    "stroke icon path data must ship inline"
  );
  for (const name of ["database", "waypoints", "settings", "search", "refresh", "chevronDown", "chevronRight", "copy", "check", "inbox", "activity"]) {
    assert.ok(
      clientSource.includes(`${name}: [["`),
      `the ${name} icon must be defined`
    );
  }
  assert.ok(
    clientSource.includes("h(Icon, { name: open ? \"chevronDown\" : \"chevronRight\""),
    "month carets must render through the Icon component"
  );
});

// Every ported label ships in both dictionaries.
test("ported features ship localized labels in both dictionaries", () => {
  for (const key of [
    "memory.explorer.tabStatus",
    "memory.explorer.loadMore",
    "memory.explorer.delete",
    "memory.explorer.confirmDelete",
    "memory.explorer.cancel",
    "memory.explorer.deleted",
    "memory.explorer.deleteFailed",
    "memory.status.memories",
    "memory.status.entities",
    "memory.status.vector",
    "memory.status.vectorOn",
    "memory.status.vectorOff",
    "memory.status.llm",
    "memory.status.llmCalls",
    "memory.status.error",
    "memory.settings.mode.title",
    "memory.settings.mode.light",
    "memory.settings.mode.standard",
    "memory.settings.mode.savedHint",
    "memory.settings.mode.offList",
    "memory.settings.extapi.title",
    "memory.settings.extapi.enabled",
    "memory.settings.extapi.disabled",
    "memory.settings.extapi.address",
    "memory.settings.extapi.port",
    "memory.settings.extapi.token",
    "memory.settings.extapi.copy",
    "memory.settings.extapi.copied",
    "memory.settings.extapi.savedHint",
    "memory.settings.extapi.invalidPort"
  ]) {
    assert.ok(
      clientSource.includes(`"${key}"`),
      `${key} key must exist`
    );
  }
});
